"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = os.environ.get('SECRET_KEY')
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 't')

if not _secret_key:
    if not DEBUG:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable is not set. "
            "This is required in production (DEBUG=False)."
        )
    # Development-only insecure fallback
    _secret_key = 'django-insecure-dev-only-do-not-use-in-production'
SECRET_KEY = _secret_key

# SECURITY WARNING: don't run with debug turned on in production!
_allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
if not _allowed_hosts_env:
    if not DEBUG:
        raise ImproperlyConfigured(
            "ALLOWED_HOSTS environment variable is not set. "
            "This is required in production (DEBUG=False)."
        )
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
else:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]

if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
    ALLOWED_HOSTS.append(os.environ.get('RENDER_EXTERNAL_HOSTNAME'))

frontend_url = os.environ.get('FRONTEND_URL', 'http://localhost:3000').rstrip('/')
# CORS_ALLOW_ALL_ORIGINS is intentionally NOT set here.
# Only explicit origins are allowed to prevent CORS misconfiguration.
CORS_ALLOWED_ORIGINS = list({
    "http://localhost:3000",
    frontend_url,
})
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'apps.accounts.apps.AccountsConfig',
    'apps.clinics.apps.ClinicsConfig',
    'apps.doctors.apps.DoctorsConfig',
    'apps.patients.apps.PatientsConfig',
    'apps.appointments.apps.AppointmentsConfig',
    'apps.audit.apps.AuditConfig',
    'apps.core.apps.CoreConfig',
    'apps.records.apps.RecordsConfig',
    'apps.prescriptions.apps.PrescriptionsConfig',
    'apps.analytics.apps.AnalyticsConfig',
    'apps.notifications.apps.NotificationsConfig',
    'apps.billing.apps.BillingConfig',
    'apps.inventory.apps.InventoryConfig',
    'apps.subscriptions.apps.SubscriptionsConfig',
    "corsheaders",
    'django_celery_beat',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", 
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.subscriptions.middleware.SubscriptionEnforcementMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ── Database ──────────────────────────────────────────────────────────────────
# In production, DATABASE_URL takes precedence.
# If DATABASE_URL is not set, all DB_* variables must be explicitly configured;
# DB_PASSWORD has NO fallback — a missing password will raise KeyError at startup.
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ['DATABASE_URL'],
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    _db_password = os.environ.get('DB_PASSWORD')
    if not _db_password:
        if not DEBUG:
            raise ImproperlyConfigured(
                "DB_PASSWORD environment variable is not set. "
                "This is required in production when DATABASE_URL is not provided."
            )
        # In dev, allow an empty password (local postgres with trust auth)
        _db_password = os.environ.get('DB_PASSWORD', '')
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'mediclinic_db'),
            'USER': os.environ.get('DB_USER', 'postgres'),
            'PASSWORD': _db_password,
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
AUTH_USER_MODEL = "accounts.User"
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "EXCEPTION_HANDLER": "config.exceptions.custom_exception_handler",
    "DEFAULT_THROTTLE_RATES": {
        "login_email": "5/15m",
        "patient_otp": "10/h",
        "mfa_strict": "5/5m",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# ── Email (Brevo SMTP Relay) ──────────────────────────────────────────────────
if DEBUG and not os.environ.get("BREVO_SMTP_LOGIN"):
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "MediClinic <anveshpandey488@gmail.com>"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp-relay.brevo.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = os.environ["BREVO_SMTP_LOGIN"]
    EMAIL_HOST_PASSWORD = os.environ["BREVO_SMTP_KEY"]
    DEFAULT_FROM_EMAIL = os.environ.get(
        "DEFAULT_FROM_EMAIL", f"MediClinic <{os.environ['BREVO_SMTP_LOGIN']}>"
    )

# ── Frontend URL (used for invite links) ─────────────────────────────────────
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

# ── Media files (profile photos etc.) ────────────────────────────────────────
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# ── Celery Configuration ──────────────────────────────────────────────────
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# In development (DEBUG=True) or when forced, run tasks synchronously — no Redis needed.
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', str(DEBUG)).lower() in ('true', '1', 't')

# ── Razorpay ──────────────────────────────────────────────────────────────────
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET')
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET')

# Plan IDs (create these in Razorpay dashboard first)
RAZORPAY_PLAN_IDS = {
    'professional': os.environ.get('RAZORPAY_PLAN_ID_PROFESSIONAL'),
    'enterprise': os.environ.get('RAZORPAY_PLAN_ID_ENTERPRISE'),
}

# Our platform GST details
PLATFORM_GSTIN = os.environ.get('PLATFORM_GSTIN', default='')
PLATFORM_NAME = 'MediClinic'
PLATFORM_ADDRESS = os.environ.get('PLATFORM_ADDRESS', default='')
HSN_SAC_CODE = '998314'  # Software SaaS services

# ── Celery Beat Schedule ──────────────────────────────────────────────────────
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'cancel-unpaid-appointments': {
        'task': 'apps.appointments.tasks.cancel_unpaid_appointments',
        'schedule': crontab(minute='*/5'),  # Every 5 minutes
    },
}

CELERY_TASK_EAGER_PROPAGATES = True

# ── Google OAuth ──────────────────────────────────────────────────────────────
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
