# Generated by Django 6.0.2 on 2026-03-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_follow_up_date_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_provider',
            field=models.CharField(blank=True, choices=[('GOOGLE_MEET', 'Google Meet'), ('ZOOM', 'Zoom'), ('CUSTOM_WEBRTC', 'Custom WebRTC')], max_length=20, null=True),
        ),
    ]
