# Generated by Django 6.0.2 on 2026-04-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_queue_token_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_virtual',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='meeting_link',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='meeting_provider',
        ),
    ]
