# Generated by Django 4.2.29 on 2026-06-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_appointment_is_virtual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_flow',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pay_now', 'Pay Now'), ('pay_at_clinic', 'Pay at Clinic')], default='not_applicable', max_length=20),
        ),
    ]
