# Generated by Django 4.2.29 on 2026-07-22 03:52

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_payment_flow_and_method'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='prevent_overlapping_appointments',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'CONFIRMED', 'WAITING', 'IN_PROGRESS'])), expressions=[('doctor_clinic', '='), ('time_range', '&&')], name='prevent_overlapping_appointments'),
        ),
    ]
