# Generated by Django 4.2.29 on 2026-07-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_remove_clinic_stripe_customer_id_and_more'),
        ('appointments', '0008_remove_appointment_prevent_overlapping_appointments_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('clinic', 'appointment_date', 'queue_token')},
        ),
    ]
