# Generated by Django 6.0.2 on 2026-08-12 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_unique_together'),
        ('clinics', '0006_remove_clinic_subscription_plan'),
        ('doctors', '0005_doctorreview'),
        ('patients', '0003_intakeform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'appointment_date'], name='appointment_clinic__843526_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['clinic', 'status'], name='appointment_clinic__02f124_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor_clinic', 'appointment_date'], name='appointment_doctor__e846f7_idx'),
        ),
    ]
