# Generated by Django 6.0.2 on 2026-06-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_clinic_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='subscription_end_date',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='subscription_status',
        ),
        migrations.AddField(
            model_name='clinic',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clinic',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clinic',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='business_pan',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='clinic',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='clinic',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='linked_account_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('kyc_submitted', 'KYC Submitted'), ('kyc_under_review', 'Under Review'), ('kyc_verified', 'Verified'), ('kyc_rejected', 'Rejected')], default='not_started', max_length=30),
        ),
        migrations.AddField(
            model_name='clinic',
            name='razorpay_linked_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
