# Generated by Django 6.0.2 on 2026-08-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0005_receptionistinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='subscription_plan',
        ),
    ]
