# Generated by Django 4.2.29 on 2026-07-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auditlog_audit_audit_timesta_19e18a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('LOCKED_OUT', 'Locked Out')], default='FAILED', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_autha_timesta_d2b13a_idx'), models.Index(fields=['email', 'timestamp'], name='audit_autha_email_bcd1cc_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_autha_ip_addr_3ef331_idx'), models.Index(fields=['endpoint', 'timestamp'], name='audit_autha_endpoin_bb5bd3_idx')],
            },
        ),
    ]
