# Generated by Django 4.2.29 on 2026-06-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_remove_paymenttransaction_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('pending', 'Pending'), ('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('pending_at_clinic', 'Pending at Clinic')], default='draft', max_length=20),
        ),
    ]
