# Generated by Django 4.2.29 on 2026-06-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_platformsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='bank_ifsc',
        ),
        migrations.RemoveField(
            model_name='platformsettings',
            name='upi_id',
        ),
    ]
