# Generated by Django 6.0.2 on 2026-08-03 03:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_bank_fields_from_platform_settings'),
        ('subscriptions', '0004_ensure_all_clinics_have_subscriptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIdempotencyKey',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(max_length=50)),
                ('reference_id', models.CharField(max_length=100)),
                ('razorpay_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('resulting_status', models.CharField(max_length=20)),
                ('source_event', models.CharField(max_length=50)),
                ('razorpay_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('idempotency_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.paymentidempotencykey')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='billing.invoice')),
                ('subscription_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='billing.subscriptioninvoice')),
            ],
            options={
                'indexes': [models.Index(fields=['invoice', 'created_at'], name='billing_pay_invoice_1d64d5_idx'), models.Index(fields=['subscription_invoice', 'created_at'], name='billing_pay_subscri_bd95f0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('invoice__isnull', False), ('subscription_invoice__isnull', True)), models.Q(('invoice__isnull', True), ('subscription_invoice__isnull', False)), _connector='OR'), name='ledger_entry_exactly_one_target')],
            },
        ),
    ]
