# Generated by Django 6.0.2 on 2026-08-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_paymentidempotencykey_paymentledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='last_failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptioninvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
