# Generated by Django 6.0.2 on 2026-08-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_paymentoutboxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
