# Generated by Django 6.0.2 on 2026-08-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_invoice_number_invoice_pdf_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('pending', 'Pending'), ('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Netbanking'), ('wallet', 'Wallet'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], default='pending', max_length=20),
        ),
    ]
