# Generated by Django 6.0.2 on 2026-08-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_refundrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_payment_attempts', models.PositiveIntegerField(default=0)),
                ('successful_payments', models.PositiveIntegerField(default=0)),
                ('failed_payments', models.PositiveIntegerField(default=0)),
                ('avg_time_to_payment_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('reconciliation_catches', models.PositiveIntegerField(default=0)),
                ('refunds_processed', models.PositiveIntegerField(default=0)),
                ('refund_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dunning_recoveries', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
