# Generated by Django 6.0.2 on 2026-06-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_checkout_session_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='clinic_gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_plan_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('halted', 'Halted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trialing', max_length=30),
        ),
    ]
