# Generated by Django 4.2.29 on 2026-07-22 04:33

from django.db import migrations
from django.utils import timezone
from datetime import timedelta

def backfill_subscriptions(apps, schema_editor):
    Clinic = apps.get_model('clinics', 'Clinic')
    Subscription = apps.get_model('subscriptions', 'Subscription')
    
    # Clinics without a subscription
    clinics_without_sub = Clinic.objects.filter(subscription__isnull=True)
    
    trial_end_date = timezone.now() + timedelta(days=14)
    
    subscriptions_to_create = []
    for clinic in clinics_without_sub:
        subscriptions_to_create.append(
            Subscription(
                clinic=clinic,
                status='trialing',
                plan='starter',
                trial_end=trial_end_date
            )
        )
        
    Subscription.objects.bulk_create(subscriptions_to_create)

def reverse_backfill(apps, schema_editor):
    pass # No need to delete them on reverse since they are meant to be there

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_remove_subscription_stripe_checkout_session_id_and_more'),
        ('clinics', '0004_remove_clinic_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_subscriptions, reverse_backfill),
    ]
