# Generated by Django 6.0.2 on 2026-08-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_ensure_all_clinics_have_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('created', 'Created'), ('active', 'Active'), ('past_due', 'Past Due'), ('halted', 'Halted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trialing', max_length=30),
        ),
    ]
