# Generated by Django 6.0.2 on 2026-08-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='dunning_stage',
            field=models.CharField(choices=[('none', 'None'), ('day_1', 'Day 1'), ('day_3', 'Day 3'), ('day_5', 'Day 5'), ('day_7_final', 'Day 7 Final')], default='none', max_length=20),
        ),
    ]
