# Generated by Django 6.0.2 on 2026-08-09 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_dunning_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DunningRecoveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dunning_stage_reached', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_logs', to='subscriptions.subscription')),
            ],
        ),
    ]
