# Generated by Django 6.0.2 on 2026-03-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Comma-separated list of known allergies', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Comma-separated list of current medications', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_completed',
            field=models.BooleanField(default=False, help_text='True once the patient has filled in their medical profile'),
        ),
    ]
