# Generated by Django 6.0.2 on 2026-03-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_queue_token_alter_appointment_status'),
        ('patients', '0002_patient_allergies_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergies_update', models.TextField(blank=True, help_text='Patient reported allergies', null=True)),
                ('current_medications_update', models.TextField(blank=True, help_text='Patient reported medications', null=True)),
                ('medical_history_notes', models.TextField(blank=True, null=True)),
                ('signature_provided', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake_form', to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_forms', to='patients.patient')),
            ],
        ),
    ]
