# Generated by Django 4.2.29 on 2026-07-22 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctorinvitetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinvitetoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 22, 5, 42, 38, 716391, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
