# Generated by Django 6.0.2 on 2026-03-13 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0002_patient_allergies_patient_blood_group_and_more'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='notes',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='doctors.doctorclinic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor_notes',
            field=models.TextField(blank=True, help_text='Public notes visible to patient'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='private_notes',
            field=models.TextField(blank=True, help_text='Private notes visible only to doctors/staff'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vitals_blood_pressure',
            field=models.CharField(blank=True, help_text='e.g. 120/80', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vitals_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='in Fahrenheit', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField(help_text='Number of days')),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='records.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Viral Fever Kit', max_length=150)),
                ('items', models.JSONField(help_text='Array of medicine objects: [{medicine_name, dosage, frequency, duration_days, instructions}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_templates', to='doctors.doctorclinic')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('doctor_clinic', 'name')},
            },
        ),
    ]
