# Generated by Django 6.0.2 on 2026-03-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.TextField(blank=True, help_text='Long-form bio shown on public profile'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='Array of {degree, institution, year}'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list, help_text='Array of language strings'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.TextField(blank=True, help_text='e.g. MBBS, MD, DNB'),
        ),
        migrations.AlterField(
            model_name='doctorclinic',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
