# Generated by Django 6.0.2 on 2026-03-15 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_about_doctor_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, help_text='Reason for time off (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctors.doctorclinic')),
            ],
        ),
    ]
