# Generated by Django 6.0.2 on 2026-03-15 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_latitude_clinic_longitude'),
        ('doctors', '0003_doctorleave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorleave',
            name='created_at',
        ),
        migrations.CreateModel(
            name='DoctorInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('specialization', models.CharField(max_length=255)),
                ('token', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_invitations', to='clinics.clinic')),
            ],
            options={
                'unique_together': {('clinic', 'email', 'status')},
            },
        ),
    ]
