# Generated by Django 6.0.2 on 2026-03-21 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_queue_token_alter_appointment_status'),
        ('doctors', '0004_remove_doctorleave_created_at_doctorinvitation'),
        ('patients', '0003_intakeform'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Optional link to the specific visit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_reviews', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('doctor', 'patient', 'appointment')},
            },
        ),
    ]
